[package]

name = "zxibs/wrapperservice"

realm = "shared"

description = "This service allows you to create custom properties for roblox instances, see the documentation for more info: (documentation is not available yet.), github: https://github.com/zxibs/WrapperService"

registry = "https://github.com/UpliftGames/wally-index"

version = "0.2.0"

license = "MIT"

include = [
    "src",
    "default.project.json"
]

exclude = [
    "debug",
    "docs",
    "src",
    "test",
    ".vscode",
    ".gitignore",
    ".styluaignore",
    "test.project.json",
    "README.md",
    "LICENSE.md",
    "wally.toml",
    "roblox.toml",
    "selene.toml",
    "stylua.toml",
    "testez-companion.toml",
    "wally.lock"
]

[dependencies]
signalservice = "zxibs/signalservice@0.2.0"