[package]
name = "redusofficial/wrapperservice"
description = "This service allows you to create custom properties for roblox instances, see the documentation for more info: https://zxibs.github.io/WrapperService/ github: https://github.com/zxibs/WrapperService"
version = "1.0.5"
license = "MIT"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["LICENSE.md", "README.md", "src", "src/**", "Packages", "Packages/**", "wally.toml", "default.project.json"]

[dependencies]
Promise = "evaera/promise@4.0.0"
Jantior = "howmanysmall/janitor@1.15.7"
t = "osyrisrblx/t@3.1.1"
Signal = "stravant/goodsignal@0.2.1"