[package]
name = "zxibs/wrapperservice"
description = "This service allows you to create custom properties for roblox instances, see the documentation for more info: https://zxibs.github.io/WrapperService/ github: https://github.com/zxibs/WrapperService"
version = "0.3.5"
license = "MIT"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["LICENSE.md", "README.md", "src", "src/**", "wally.toml", "default.project.json"]

[dependencies]
SignalService = "zxibs/signalservice@^0"
t = "osyrisrblx/t@^3"
