name: Lint and Format using Selene and StyLua

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        run: |
          rm -f roblox.toml
          selene generate-roblox-std
          selene src/

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files in folder src
        id: git-check
        run: echo ::set-output name=modified::$(if git diff --quiet HEAD main -- src; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github Actions'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add src
          git commit -m "Formatted code using StyLua"
          git push