name: Release

on: workflow_dispatch

jobs:
  test:
    name: test echo output
    runs-on: ubuntu-latest
  steps:
    - name: echo
      shell: bash
      env:
        WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
      run: |
        echo -e '[tokens]\n"https://api.wally.run/" = "$WALLY_AUTH"'
